-- =========================================================
-- PROJETO: Sistema de Acompanhamento e Avaliação de Séries de TV
-- DISCIPLINA: Banco de Dados I - UNESP/FC
-- SGBD: PostgreSQL
-- =========================================================
-- Este script implementa a modelagem física do projeto.
-- A ordem de criação e inserção segue a ordem de dependência
-- apresentada no modelo lógico.
-- =========================================================

-- ---------------------------------------------------------
-- 1. CRIAÇÃO DO ESQUEMA
-- RN01-RN24: os objetos do projeto ficam isolados de public.
-- ---------------------------------------------------------
DROP SCHEMA IF EXISTS serie_tracker CASCADE;
CREATE SCHEMA serie_tracker;
SET search_path TO serie_tracker;

-- =========================================================
-- 2. DDL - CRIAÇÃO DAS TABELAS
-- =========================================================

-- ---------------------------------------------------------
-- 2.1 Usuários
-- RN01: username e email são únicos; username segue o padrão
--       letras minúsculas, dígitos e sublinhado, de 3 a 30 chars.
-- ---------------------------------------------------------
CREATE TABLE usuario (
    id_usuario      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR(30)  NOT NULL,
    email          VARCHAR(120) NOT NULL,
    nome_exibicao   VARCHAR(60),
    bio             TEXT,
    data_cadastro   DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_username UNIQUE (username),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_username
        CHECK (username ~ '^[a-z0-9_]{3,30}$')
);

-- ---------------------------------------------------------
-- 2.2 Relação social de seguidores
-- RN02: seguir é unidirecional.
-- RN03: um usuário não pode seguir a si mesmo.
-- RN04: exclusão de usuário remove seus relacionamentos sociais.
-- ---------------------------------------------------------
CREATE TABLE segue (
    id_seguidor INTEGER NOT NULL,
    id_seguido  INTEGER NOT NULL,
    data_inicio DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT pk_segue PRIMARY KEY (id_seguidor, id_seguido),
    CONSTRAINT fk_segue_seguidor
        FOREIGN KEY (id_seguidor)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_segue_seguido
        FOREIGN KEY (id_seguido)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT ck_segue_nao_auto
        CHECK (id_seguidor <> id_seguido)
);

-- ---------------------------------------------------------
-- 2.3 Séries
-- ---------------------------------------------------------
CREATE TABLE serie (
    id_serie       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    titulo         VARCHAR(150) NOT NULL,
    titulo_original VARCHAR(150),
    sinopse        TEXT,
    ano_estreia    INTEGER,
    situacao       VARCHAR(15) NOT NULL,
    pais_origem    VARCHAR(2),

    CONSTRAINT pk_serie PRIMARY KEY (id_serie),
    CONSTRAINT ck_serie_situacao
        CHECK (situacao IN ('em_exibicao', 'encerrada', 'cancelada')),
    CONSTRAINT ck_serie_pais
        CHECK (pais_origem IS NULL OR char_length(pais_origem) = 2)
);

-- ---------------------------------------------------------
-- 2.4 Temporadas - entidade fraca
-- RN06: toda temporada pertence a uma série; número único
--       dentro da série.
-- RN08: dependência existencial em relação à série.
-- ---------------------------------------------------------
CREATE TABLE temporada (
    id_temporada INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_serie     INTEGER NOT NULL,
    numero       INTEGER NOT NULL,
    titulo       VARCHAR(100),
    data_estreia DATE,

    CONSTRAINT pk_temporada PRIMARY KEY (id_temporada),
    CONSTRAINT uk_temporada_serie_numero UNIQUE (id_serie, numero),
    CONSTRAINT fk_temporada_serie
        FOREIGN KEY (id_serie)
        REFERENCES serie (id_serie)
        ON DELETE CASCADE,
    CONSTRAINT ck_temporada_numero
        CHECK (numero > 0)
);

-- ---------------------------------------------------------
-- 2.5 Episódios - entidade fraca
-- RN07: toda episódio pertence a uma temporada; número único
--       dentro da temporada.
-- RN08: dependência existencial em relação à série/temporada.
-- ---------------------------------------------------------
CREATE TABLE episodio (
    id_episodio   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_temporada  INTEGER NOT NULL,
    numero        INTEGER NOT NULL,
    titulo        VARCHAR(150) NOT NULL,
    duracao_min   INTEGER,
    data_exibicao DATE,
    sinopse       TEXT,

    CONSTRAINT pk_episodio PRIMARY KEY (id_episodio),
    CONSTRAINT uk_episodio_temporada_numero UNIQUE (id_temporada, numero),
    CONSTRAINT fk_episodio_temporada
        FOREIGN KEY (id_temporada)
        REFERENCES temporada (id_temporada)
        ON DELETE CASCADE,
    CONSTRAINT ck_episodio_numero
        CHECK (numero > 0),
    CONSTRAINT ck_episodio_duracao
        CHECK (duracao_min IS NULL OR duracao_min > 0),
    -- RN12: não é permitido registrar episódio com data original futura.
    CONSTRAINT ck_episodio_data_exibicao
        CHECK (data_exibicao IS NULL OR data_exibicao <= CURRENT_DATE)
);

-- ---------------------------------------------------------
-- 2.6 Gêneros
-- RN05: nome do gênero é único.
-- A participação mínima de toda série em serie_genero (>= 1)
-- não é exprimível apenas por NOT NULL/UNIQUE/FK; a carga e a
-- camada de aplicação garantem que nenhuma série fique sem gênero.
-- ---------------------------------------------------------
CREATE TABLE genero (
    id_genero INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome      VARCHAR(40) NOT NULL,

    CONSTRAINT pk_genero PRIMARY KEY (id_genero),
    CONSTRAINT uk_genero_nome UNIQUE (nome)
);

-- ---------------------------------------------------------
-- 2.7 Classificação série-gênero
-- RN05: relacionamento N:N.
-- ---------------------------------------------------------
CREATE TABLE serie_genero (
    id_serie  INTEGER NOT NULL,
    id_genero INTEGER NOT NULL,

    CONSTRAINT pk_serie_genero PRIMARY KEY (id_serie, id_genero),
    CONSTRAINT fk_serie_genero_serie
        FOREIGN KEY (id_serie)
        REFERENCES serie (id_serie)
        ON DELETE CASCADE,
    CONSTRAINT fk_serie_genero_genero
        FOREIGN KEY (id_genero)
        REFERENCES genero (id_genero)
        ON DELETE CASCADE
);

-- ---------------------------------------------------------
-- 2.8 Pessoas do meio audiovisual
-- ---------------------------------------------------------
CREATE TABLE pessoa (
    id_pessoa       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(120) NOT NULL,
    data_nascimento DATE,
    nacionalidade   VARCHAR(60),

    CONSTRAINT pk_pessoa PRIMARY KEY (id_pessoa)
);

-- ---------------------------------------------------------
-- 2.9 Participações
-- RN09: uma pessoa pode exercer mais de uma função na mesma série.
-- RN10: personagem só existe para a função ator.
-- ---------------------------------------------------------
CREATE TABLE participacao (
    id_pessoa  INTEGER NOT NULL,
    id_serie   INTEGER NOT NULL,
    funcao     VARCHAR(20) NOT NULL,
    personagem VARCHAR(120),

    CONSTRAINT pk_participacao PRIMARY KEY (id_pessoa, id_serie, funcao),
    CONSTRAINT fk_participacao_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoa (id_pessoa)
        ON DELETE CASCADE,
    CONSTRAINT fk_participacao_serie
        FOREIGN KEY (id_serie)
        REFERENCES serie (id_serie)
        ON DELETE CASCADE,
    CONSTRAINT ck_participacao_funcao
        CHECK (funcao IN ('ator', 'diretor', 'roteirista', 'criador')),
    CONSTRAINT ck_participacao_personagem
        CHECK (
            (funcao = 'ator' AND personagem IS NOT NULL)
            OR
            (funcao <> 'ator' AND personagem IS NULL)
        )
);

-- ---------------------------------------------------------
-- 2.10 Estado declarado da série
-- RN13: no máximo um estado por usuário e série (PK composta).
-- RN14: registros de exibição promovem o estado para assistindo;
--       o gatilho correspondente é criado posteriormente.
-- ---------------------------------------------------------
CREATE TABLE estado_serie (
    id_usuario       INTEGER NOT NULL,
    id_serie         INTEGER NOT NULL,
    estado           VARCHAR(15) NOT NULL,
    data_atualizacao DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT pk_estado_serie PRIMARY KEY (id_usuario, id_serie),
    CONSTRAINT fk_estado_serie_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_estado_serie_serie
        FOREIGN KEY (id_serie)
        REFERENCES serie (id_serie)
        ON DELETE RESTRICT,
    CONSTRAINT ck_estado_serie_estado
        CHECK (estado IN ('watchlist', 'assistindo', 'abandonada'))
);

-- ---------------------------------------------------------
-- 2.11 Histórico de exibição
-- RN11: o mesmo episódio pode ser registrado várias vezes,
--       desde que a data do evento seja diferente.
-- RN12: data_assistido não pode ser futura.
-- RN14: AFTER INSERT promove a série a assistindo.
-- ---------------------------------------------------------
CREATE TABLE registro (
    id_registro   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario    INTEGER NOT NULL,
    id_episodio   INTEGER NOT NULL,
    data_assistido DATE NOT NULL,

    CONSTRAINT pk_registro PRIMARY KEY (id_registro),
    CONSTRAINT uk_registro_evento UNIQUE
        (id_usuario, id_episodio, data_assistido),
    CONSTRAINT fk_registro_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_registro_episodio
        FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio)
        ON DELETE RESTRICT,
    CONSTRAINT ck_registro_data
        CHECK (data_assistido <= CURRENT_DATE)
);

-- ---------------------------------------------------------
-- 2.12 Avaliação - superclasse
-- RN15: avaliação pertence a um usuário e possui um tipo de alvo.
-- RN16: nota entre 0,5 e 5,0, em incrementos de 0,5.
-- RN17: nota ou texto é obrigatório.
-- RN20: contem_spoiler sinaliza spoiler.
-- total_curtidas é atributo derivado materializado; o gatilho de
-- sincronização é criado posteriormente.
-- ---------------------------------------------------------
CREATE TABLE avaliacao (
    id_avaliacao    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      INTEGER NOT NULL,
    nota            NUMERIC(2,1),
    texto           TEXT,
    contem_spoiler  BOOLEAN NOT NULL DEFAULT FALSE,
    data_publicacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_alvo       VARCHAR(10) NOT NULL,
    total_curtidas  INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT pk_avaliacao PRIMARY KEY (id_avaliacao),
    CONSTRAINT fk_avaliacao_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT ck_avaliacao_nota
        CHECK (
            nota IS NULL
            OR (
                nota >= 0.5
                AND nota <= 5.0
                AND MOD(nota * 10, 5) = 0
            )
        ),
    CONSTRAINT ck_avaliacao_nao_vazia
        CHECK (nota IS NOT NULL OR texto IS NOT NULL),
    CONSTRAINT ck_avaliacao_tipo_alvo
        CHECK (tipo_alvo IN ('serie', 'temporada', 'episodio')),
    CONSTRAINT ck_avaliacao_total_curtidas
        CHECK (total_curtidas >= 0)
);

-- ---------------------------------------------------------
-- 2.13-2.15 Especialização da avaliação
-- Estratégia (b): superclasse + uma relação por subclasse.
-- A PK da subclasse também é FK para avaliacao.
-- RN18 é garantida por trigger na avaliação de episódio.
-- RN19/disjunção são reforçadas pelos gatilhos das subclasses.
-- A totalidade da especialização é garantida pelo processo de
-- inserção: avaliação + uma subclasse devem ser criadas na mesma
-- transação.
-- ---------------------------------------------------------
CREATE TABLE avaliacao_serie (
    id_avaliacao INTEGER NOT NULL,
    id_serie     INTEGER NOT NULL,

    CONSTRAINT pk_avaliacao_serie PRIMARY KEY (id_avaliacao),
    CONSTRAINT fk_avaliacao_serie_avaliacao
        FOREIGN KEY (id_avaliacao)
        REFERENCES avaliacao (id_avaliacao)
        ON DELETE CASCADE,
    CONSTRAINT fk_avaliacao_serie_serie
        FOREIGN KEY (id_serie)
        REFERENCES serie (id_serie)
        ON DELETE RESTRICT
);

CREATE TABLE avaliacao_temporada (
    id_avaliacao INTEGER NOT NULL,
    id_temporada INTEGER NOT NULL,

    CONSTRAINT pk_avaliacao_temporada PRIMARY KEY (id_avaliacao),
    CONSTRAINT fk_avaliacao_temporada_avaliacao
        FOREIGN KEY (id_avaliacao)
        REFERENCES avaliacao (id_avaliacao)
        ON DELETE CASCADE,
    CONSTRAINT fk_avaliacao_temporada_temporada
        FOREIGN KEY (id_temporada)
        REFERENCES temporada (id_temporada)
        ON DELETE RESTRICT
);

CREATE TABLE avaliacao_episodio (
    id_avaliacao INTEGER NOT NULL,
    id_episodio  INTEGER NOT NULL,

    CONSTRAINT pk_avaliacao_episodio PRIMARY KEY (id_avaliacao),
    CONSTRAINT fk_avaliacao_episodio_avaliacao
        FOREIGN KEY (id_avaliacao)
        REFERENCES avaliacao (id_avaliacao)
        ON DELETE CASCADE,
    CONSTRAINT fk_avaliacao_episodio_episodio
        FOREIGN KEY (id_episodio)
        REFERENCES episodio (id_episodio)
        ON DELETE RESTRICT
);

-- ---------------------------------------------------------
-- 2.16 Curtidas
-- RN21: uma curtida por usuário e avaliação (PK composta).
-- RN22: ninguém pode curtir a própria avaliação; trigger abaixo.
-- RN24: exclusão de avaliação exclui suas curtidas.
-- ---------------------------------------------------------
CREATE TABLE curtida (
    id_usuario    INTEGER NOT NULL,
    id_avaliacao  INTEGER NOT NULL,
    data_curtida  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_curtida PRIMARY KEY (id_usuario, id_avaliacao),
    CONSTRAINT fk_curtida_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_curtida_avaliacao
        FOREIGN KEY (id_avaliacao)
        REFERENCES avaliacao (id_avaliacao)
        ON DELETE CASCADE
);

-- ---------------------------------------------------------
-- 2.17 Comentários
-- RN23: resposta opcional a outro comentário da mesma avaliação.
-- O FK composto (id_comentario_pai, id_avaliacao) garante que o pai
-- pertence à mesma avaliação do comentário filho.
-- RN24: exclusão de avaliação remove seus comentários.
-- ---------------------------------------------------------
CREATE TABLE comentario (
    id_comentario     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_avaliacao      INTEGER NOT NULL,
    id_usuario        INTEGER NOT NULL,
    id_comentario_pai INTEGER,
    texto             TEXT NOT NULL,
    data_publicacao   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_comentario PRIMARY KEY (id_comentario),
    CONSTRAINT uk_comentario_id_avaliacao UNIQUE (id_comentario, id_avaliacao),
    CONSTRAINT fk_comentario_avaliacao
        FOREIGN KEY (id_avaliacao)
        REFERENCES avaliacao (id_avaliacao)
        ON DELETE CASCADE,
    CONSTRAINT fk_comentario_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_comentario_pai_mesma_avaliacao
        FOREIGN KEY (id_comentario_pai, id_avaliacao)
        REFERENCES comentario (id_comentario, id_avaliacao)
        ON DELETE CASCADE,
    CONSTRAINT ck_comentario_nao_vazio
        CHECK (btrim(texto) <> '')
);

-- =========================================================
-- 3. FUNÇÕES E GATILHOS
-- =========================================================

-- ---------------------------------------------------------
-- Trigger 1 - RN18
-- Antes de inserir uma avaliação de episódio, verifica se o autor
-- já registrou aquele episódio como assistido.
-- Necessita consultar registro e avaliacao, logo não pode ser CHECK.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_avaliacao_exige_registro()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_usuario INTEGER;
BEGIN
    SELECT id_usuario
      INTO v_usuario
      FROM avaliacao
     WHERE id_avaliacao = NEW.id_avaliacao;

    IF NOT EXISTS (
        SELECT 1
          FROM registro
         WHERE id_usuario = v_usuario
           AND id_episodio = NEW.id_episodio
    ) THEN
        RAISE EXCEPTION
            'RN18: o usuário % não possui registro de exibição do episódio %',
            v_usuario, NEW.id_episodio;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_avaliacao_exige_registro
BEFORE INSERT ON avaliacao_episodio
FOR EACH ROW
EXECUTE FUNCTION fn_avaliacao_exige_registro();

-- ---------------------------------------------------------
-- Trigger 2 - RN19 + disjunção da especialização
-- Garante no máximo uma avaliação do mesmo usuário para o mesmo alvo
-- e impede que a mesma avaliação seja inserida em duas subclasses.
-- A regra compara dados distribuídos entre avaliacao e a subclasse.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_avaliacao_unica_por_alvo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_usuario INTEGER;
    v_tipo    VARCHAR(10);
    v_count   INTEGER;
BEGIN
    SELECT id_usuario, tipo_alvo
      INTO v_usuario, v_tipo
      FROM avaliacao
     WHERE id_avaliacao = NEW.id_avaliacao;

    IF v_tipo <> TG_TABLE_NAME
       AND NOT (
            (TG_TABLE_NAME = 'avaliacao_serie' AND v_tipo = 'serie')
         OR (TG_TABLE_NAME = 'avaliacao_temporada' AND v_tipo = 'temporada')
         OR (TG_TABLE_NAME = 'avaliacao_episodio' AND v_tipo = 'episodio')
       ) THEN
        RAISE EXCEPTION
            'Tipo de alvo incompatível: avaliação % foi criada como %, mas está sendo ligada a %',
            NEW.id_avaliacao, v_tipo, TG_TABLE_NAME;
    END IF;

    -- Disjunção: uma avaliação só pode pertencer a uma das três subclasses.
    SELECT COUNT(*)
      INTO v_count
      FROM (
            SELECT id_avaliacao FROM avaliacao_serie
             WHERE id_avaliacao = NEW.id_avaliacao
            UNION ALL
            SELECT id_avaliacao FROM avaliacao_temporada
             WHERE id_avaliacao = NEW.id_avaliacao
            UNION ALL
            SELECT id_avaliacao FROM avaliacao_episodio
             WHERE id_avaliacao = NEW.id_avaliacao
      ) AS subtipos;

    IF v_count > 0 THEN
        RAISE EXCEPTION
            'A avaliação % já está associada a uma subclasse de alvo',
            NEW.id_avaliacao;
    END IF;

    -- Unicidade usuário + alvo.
    IF TG_TABLE_NAME = 'avaliacao_serie' THEN
        IF EXISTS (
            SELECT 1
              FROM avaliacao a
              JOIN avaliacao_serie avs
                ON avs.id_avaliacao = a.id_avaliacao
             WHERE a.id_usuario = v_usuario
               AND avs.id_serie = NEW.id_serie
        ) THEN
            RAISE EXCEPTION
                'RN19: o usuário % já possui avaliação para a série %',
                v_usuario, NEW.id_serie;
        END IF;

    ELSIF TG_TABLE_NAME = 'avaliacao_temporada' THEN
        IF EXISTS (
            SELECT 1
              FROM avaliacao a
              JOIN avaliacao_temporada avt
                ON avt.id_avaliacao = a.id_avaliacao
             WHERE a.id_usuario = v_usuario
               AND avt.id_temporada = NEW.id_temporada
        ) THEN
            RAISE EXCEPTION
                'RN19: o usuário % já possui avaliação para a temporada %',
                v_usuario, NEW.id_temporada;
        END IF;

    ELSIF TG_TABLE_NAME = 'avaliacao_episodio' THEN
        IF EXISTS (
            SELECT 1
              FROM avaliacao a
              JOIN avaliacao_episodio ave
                ON ave.id_avaliacao = a.id_avaliacao
             WHERE a.id_usuario = v_usuario
               AND ave.id_episodio = NEW.id_episodio
        ) THEN
            RAISE EXCEPTION
                'RN19: o usuário % já possui avaliação para o episódio %',
                v_usuario, NEW.id_episodio;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_avaliacao_unica_por_alvo
BEFORE INSERT ON avaliacao_serie
FOR EACH ROW
EXECUTE FUNCTION fn_avaliacao_unica_por_alvo();

CREATE TRIGGER trg_avaliacao_unica_por_alvo_temporada
BEFORE INSERT ON avaliacao_temporada
FOR EACH ROW
EXECUTE FUNCTION fn_avaliacao_unica_por_alvo();

CREATE TRIGGER trg_avaliacao_unica_por_alvo_episodio
BEFORE INSERT ON avaliacao_episodio
FOR EACH ROW
EXECUTE FUNCTION fn_avaliacao_unica_por_alvo();

-- ---------------------------------------------------------
-- Trigger 3 - RN22
-- Impede que o autor da avaliação curta a própria avaliação.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_bloqueia_autocurtida()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_autor INTEGER;
BEGIN
    SELECT id_usuario
      INTO v_autor
      FROM avaliacao
     WHERE id_avaliacao = NEW.id_avaliacao;

    IF v_autor = NEW.id_usuario THEN
        RAISE EXCEPTION
            'RN22: o usuário % não pode curtir a própria avaliação %',
            NEW.id_usuario, NEW.id_avaliacao;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_bloqueia_autocurtida
BEFORE INSERT ON curtida
FOR EACH ROW
EXECUTE FUNCTION fn_bloqueia_autocurtida();

-- ---------------------------------------------------------
-- Trigger 4 - atributo derivado total_curtidas
-- Depois de inserir/remover uma curtida, recalcula a quantidade real.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_atualiza_contador_curtidas()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_avaliacao INTEGER;
BEGIN
    v_id_avaliacao := COALESCE(NEW.id_avaliacao, OLD.id_avaliacao);

    UPDATE avaliacao
       SET total_curtidas = (
           SELECT COUNT(*)
             FROM curtida
            WHERE id_avaliacao = v_id_avaliacao
       )
     WHERE id_avaliacao = v_id_avaliacao;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_atualiza_contador_curtidas
AFTER INSERT OR DELETE ON curtida
FOR EACH ROW
EXECUTE FUNCTION fn_atualiza_contador_curtidas();

-- ---------------------------------------------------------
-- Trigger 5 - RN14
-- Ao registrar um episódio, obtém a série correspondente e cria
-- ou promove o estado do usuário para 'assistindo'.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_garante_estado_assistindo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_serie INTEGER;
BEGIN
    SELECT t.id_serie
      INTO v_serie
      FROM episodio e
      JOIN temporada t
        ON t.id_temporada = e.id_temporada
     WHERE e.id_episodio = NEW.id_episodio;

    INSERT INTO estado_serie (id_usuario, id_serie, estado, data_atualizacao)
    VALUES (NEW.id_usuario, v_serie, 'assistindo', CURRENT_DATE)
    ON CONFLICT (id_usuario, id_serie)
    DO UPDATE SET
        estado = 'assistindo',
        data_atualizacao = CURRENT_DATE;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_garante_estado_assistindo
AFTER INSERT ON registro
FOR EACH ROW
EXECUTE FUNCTION fn_garante_estado_assistindo();

-- =========================================================
-- 4. VISÕES
-- =========================================================

-- ---------------------------------------------------------
-- 4.1 Visão unificada das avaliações
-- UNION ALL recompõe, para leitura, a fragmentação criada pela
-- especialização da entidade avaliacao.
-- ---------------------------------------------------------
CREATE OR REPLACE VIEW vw_avaliacao_completa AS
SELECT
    a.id_avaliacao,
    a.id_usuario,
    u.username,
    a.nota,
    a.texto,
    a.contem_spoiler,
    a.data_publicacao,
    a.tipo_alvo,
    a.total_curtidas,
    s.id_serie,
    NULL::INTEGER AS id_temporada,
    NULL::INTEGER AS id_episodio,
    s.titulo AS titulo_alvo
FROM avaliacao a
JOIN usuario u
  ON u.id_usuario = a.id_usuario
JOIN avaliacao_serie avs
  ON avs.id_avaliacao = a.id_avaliacao
JOIN serie s
  ON s.id_serie = avs.id_serie

UNION ALL

SELECT
    a.id_avaliacao,
    a.id_usuario,
    u.username,
    a.nota,
    a.texto,
    a.contem_spoiler,
    a.data_publicacao,
    a.tipo_alvo,
    a.total_curtidas,
    s.id_serie,
    t.id_temporada,
    NULL::INTEGER AS id_episodio,
    s.titulo || ' - Temporada ' || t.numero::TEXT
        || CASE
               WHEN t.titulo IS NOT NULL THEN ' (' || t.titulo || ')'
               ELSE ''
           END AS titulo_alvo
FROM avaliacao a
JOIN usuario u
  ON u.id_usuario = a.id_usuario
JOIN avaliacao_temporada avt
  ON avt.id_avaliacao = a.id_avaliacao
JOIN temporada t
  ON t.id_temporada = avt.id_temporada
JOIN serie s
  ON s.id_serie = t.id_serie

UNION ALL

SELECT
    a.id_avaliacao,
    a.id_usuario,
    u.username,
    a.nota,
    a.texto,
    a.contem_spoiler,
    a.data_publicacao,
    a.tipo_alvo,
    a.total_curtidas,
    s.id_serie,
    t.id_temporada,
    e.id_episodio,
    s.titulo || ' - T' || t.numero::TEXT
        || 'E' || e.numero::TEXT
        || ': ' || e.titulo AS titulo_alvo
FROM avaliacao a
JOIN usuario u
  ON u.id_usuario = a.id_usuario
JOIN avaliacao_episodio ave
  ON ave.id_avaliacao = a.id_avaliacao
JOIN episodio e
  ON e.id_episodio = ave.id_episodio
JOIN temporada t
  ON t.id_temporada = e.id_temporada
JOIN serie s
  ON s.id_serie = t.id_serie;

-- ---------------------------------------------------------
-- 4.2 Progresso por usuário e série
-- RN11 exige COUNT(DISTINCT id_episodio), pois reexibições não
-- podem aumentar artificialmente o percentual de progresso.
-- ---------------------------------------------------------
CREATE OR REPLACE VIEW vw_progresso_serie AS
SELECT
    es.id_usuario,
    es.id_serie,
    s.titulo,
    es.estado,
    COUNT(DISTINCT r.id_episodio) AS episodios_assistidos,
    COUNT(DISTINCT e.id_episodio) AS total_episodios,
    ROUND(
        100.0 * COUNT(DISTINCT r.id_episodio)
        / NULLIF(COUNT(DISTINCT e.id_episodio), 0),
        2
    ) AS percentual_progresso
FROM estado_serie es
JOIN serie s
  ON s.id_serie = es.id_serie
JOIN temporada t
  ON t.id_serie = es.id_serie
JOIN episodio e
  ON e.id_temporada = t.id_temporada
LEFT JOIN registro r
  ON r.id_usuario = es.id_usuario
 AND r.id_episodio = e.id_episodio
GROUP BY
    es.id_usuario,
    es.id_serie,
    s.titulo,
    es.estado;

-- =========================================================
-- 5. CARGA DE DADOS - DML
-- =========================================================

-- ---------------------------------------------------------
-- 5.1 Usuários (6 registros)
-- ---------------------------------------------------------
INSERT INTO usuario
(id_usuario, username, email, nome_exibicao, bio, data_cadastro)
VALUES
(1, 'ana_dev',     'ana@example.com',     'Ana',     'Apaixonada por ficcao cientifica.', '2026-01-10'),
(2, 'bruno_db',    'bruno@example.com',   'Bruno',   'Gosta de series policiais.',      '2026-01-12'),
(3, 'carla_ui',    'carla@example.com',   'Carla',   'Maratonista de dramas.',           '2026-01-15'),
(4, 'diego_code',  'diego@example.com',   'Diego',   'Sempre em busca de uma boa comedia.', '2026-01-18'),
(5, 'elisa_data',  'elisa@example.com',   'Elisa',   'Curte analisar roteiros.',         '2026-01-20'),
(6, 'fabio_net',   'fabio@example.com',   'Fabio',   'Fã de fantasia e aventura.',        '2026-01-25');

-- ---------------------------------------------------------
-- 5.2 Seguidores
-- Há relações não recíprocas para demonstrar a RN02.
-- ---------------------------------------------------------
INSERT INTO segue
(id_seguidor, id_seguido, data_inicio)
VALUES
(1, 2, '2026-02-01'),
(1, 3, '2026-02-02'),
(2, 3, '2026-02-03'),
(3, 1, '2026-02-04'),
(4, 1, '2026-02-05'),
(5, 1, '2026-02-06'),
(6, 2, '2026-02-07');

-- ---------------------------------------------------------
-- 5.3 Séries (5 registros)
-- ---------------------------------------------------------
INSERT INTO serie
(id_serie, titulo, titulo_original, sinopse, ano_estreia, situacao, pais_origem)
VALUES
(1, 'Stranger Things', 'Stranger Things', 'Jovens investigam acontecimentos sobrenaturais em uma pequena cidade.', 2016, 'em_exibicao', 'US'),
(2, 'The Office', 'The Office', 'Rotina de funcionários de um escritório acompanhada em estilo documental.', 2005, 'encerrada', 'US'),
(3, 'Dark', 'Dark', 'Uma cidade pequena é marcada por desaparecimentos e misterios envolvendo o tempo.', 2017, 'encerrada', 'DE'),
(4, 'Breaking Bad', 'Breaking Bad', 'Um professor de quimica entra no mundo do crime para garantir o futuro da familia.', 2008, 'encerrada', 'US'),
(5, 'Arcane', 'Arcane', 'Duas cidades divididas entram em conflito enquanto duas irmas seguem caminhos opostos.', 2021, 'em_exibicao', 'US');

-- ---------------------------------------------------------
-- 5.4 Temporadas (2 por série = 10 registros)
-- ---------------------------------------------------------
INSERT INTO temporada
(id_temporada, id_serie, numero, titulo, data_estreia)
VALUES
(1, 1, 1, 'Temporada 1', '2016-07-15'),
(2, 1, 2, 'Temporada 2', '2017-10-27'),
(3, 2, 1, 'Temporada 1', '2005-03-24'),
(4, 2, 2, 'Temporada 2', '2005-09-15'),
(5, 3, 1, 'Temporada 1', '2017-12-01'),
(6, 3, 2, 'Temporada 2', '2019-06-21'),
(7, 4, 1, 'Temporada 1', '2008-01-20'),
(8, 4, 2, 'Temporada 2', '2009-03-08'),
(9, 5, 1, 'Ato 1', '2021-11-06'),
(10, 5, 2, 'Ato 2', '2024-11-09');

-- ---------------------------------------------------------
-- 5.5 Episódios (6 por temporada = 60 registros)
-- ---------------------------------------------------------
INSERT INTO episodio
(id_episodio, id_temporada, numero, titulo, duracao_min, data_exibicao, sinopse)
VALUES
-- Stranger Things S1
(1, 1, 1, 'The Vanishing of Will Byers', 49, '2016-07-15', 'Will desaparece após uma noite de misterio.'),
(2, 1, 2, 'The Weirdo on Maple Street', 56, '2016-07-15', 'Uma garota misteriosa cruza o caminho dos meninos.'),
(3, 1, 3, 'Holly, Jolly', 52, '2016-07-15', 'As investigações sobre o desaparecimento avancam.'),
(4, 1, 4, 'The Body', 51, '2016-07-15', 'A familia recebe uma noticia devastadora.'),
(5, 1, 5, 'The Flea and the Acrobat', 53, '2016-07-15', 'Os jovens tentam entender uma dimensão paralela.'),
(6, 1, 6, 'The Monster', 47, '2016-07-15', 'O grupo enfrenta uma ameaça sobrenatural.'),
-- Stranger Things S2
(7, 2, 1, 'MADMAX', 48, '2017-10-27', 'Uma nova presença altera a rotina de Hawkins.'),
(8, 2, 2, 'Trick or Treat, Freak', 48, '2017-10-27', 'O Halloween termina em uma situação perigosa.'),
(9, 2, 3, 'The Pollywog', 51, '2017-10-27', 'A descoberta de uma criatura gera suspeitas.'),
(10, 2, 4, 'Will the Wise', 46, '2017-10-27', 'Will passa por mudanças cada vez mais estranhas.'),
(11, 2, 5, 'Dig Dug', 58, '2017-10-27', 'O grupo procura respostas sobre o subterraneo.'),
(12, 2, 6, 'The Spy', 51, '2017-10-27', 'A ameaça atinge um novo nivel.'),
-- The Office S1
(13, 3, 1, 'Pilot', 22, '2005-03-24', 'Apresentacao dos funcionarios da filial de Scranton.'),
(14, 3, 2, 'Diversity Day', 22, '2005-03-29', 'A filial promove uma atividade sobre diversidade.'),
(15, 3, 3, 'Health Care', 22, '2005-04-05', 'O escritorio discute seu novo plano de saude.'),
(16, 3, 4, 'The Alliance', 22, '2005-04-12', 'Uma alianca surge diante dos rumores de demissao.'),
(17, 3, 5, 'Basketball', 22, '2005-04-19', 'Funcionarios disputam uma partida amistosa.'),
(18, 3, 6, 'Hot Girl', 22, '2005-04-26', 'Uma vendedora de bolsas visita o escritorio.'),
-- The Office S2
(19, 4, 1, 'The Dundies', 22, '2005-09-20', 'Michael organiza a premiacao anual do escritorio.'),
(20, 4, 2, 'Sexual Harassment', 22, '2005-09-27', 'A empresa revisita suas regras de conduta.'),
(21, 4, 3, 'Office Olympics', 22, '2005-10-04', 'Os funcionarios inventam suas proprias competicoes.'),
(22, 4, 4, 'The Fire', 22, '2005-10-11', 'Um incidente provoca evacuacao do escritorio.'),
(23, 4, 5, 'Halloween', 22, '2005-10-18', 'O Halloween traz mais confusao ao escritorio.'),
(24, 4, 6, 'The Fight', 22, '2005-11-01', 'Uma disputa entre funcionarios esquenta o ambiente.'),
-- Dark S1
(25, 5, 1, 'Segredos', 51, '2017-12-01', 'O desaparecimento de uma crianca mobiliza Winden.'),
(26, 5, 2, 'Mentiras', 44, '2017-12-01', 'Familias escondem informacoes importantes.'),
(27, 5, 3, 'Passado e presente', 45, '2017-12-01', 'O misterio ganha uma nova dimensao temporal.'),
(28, 5, 4, 'Dupla vida', 50, '2017-12-01', 'As conexoes entre os personagens se intensificam.'),
(29, 5, 5, 'Verdades', 47, '2017-12-01', 'Novas pistas aproximam a cidade da verdade.'),
(30, 5, 6, 'Alfa e Omega', 50, '2017-12-01', 'A temporada revela uma parte central do misterio.'),
-- Dark S2
(31, 6, 1, 'Beginnings and Endings', 53, '2019-06-21', 'O ciclo se fecha e reabre ao mesmo tempo.'),
(32, 6, 2, 'Dark Matter', 54, '2019-06-21', 'A pesquisa sobre a origem do misterio avanca.'),
(33, 6, 3, 'Ghosts', 52, '2019-06-21', 'O passado continua interferindo no presente.'),
(34, 6, 4, 'The Travelers', 55, '2019-06-21', 'Diferentes grupos tentam alterar os acontecimentos.'),
(35, 6, 5, 'Lost and Found', 56, '2019-06-21', 'Personagens descobrem novas pistas.'),
(36, 6, 6, 'Endings and Beginnings', 56, '2019-06-21', 'O ciclo chega a uma nova virada.'),
-- Breaking Bad S1
(37, 7, 1, 'Pilot', 58, '2008-01-20', 'Walter White entra no mundo da producao de metanfetamina.'),
(38, 7, 2, 'Cat in the Bag', 48, '2008-01-27', 'Os parceiros precisam lidar com as consequencias.'),
(39, 7, 3, '...And the Bag''s in the River', 48, '2008-02-03', 'A situacao se torna cada vez mais perigosa.'),
(40, 7, 4, 'Cancer Man', 48, '2008-02-10', 'Walter revela uma noticia importante.'),
(41, 7, 5, 'Gray Matter', 49, '2008-02-17', 'Relacoes antigas voltam a interferir nas escolhas.'),
(42, 7, 6, 'Crazy Handful of Nothin''', 47, '2008-02-24', 'Walter assume uma nova postura.'),
-- Breaking Bad S2
(43, 8, 1, 'Seven Thirty-Seven', 47, '2009-03-08', 'A dupla estabelece uma nova meta financeira.'),
(44, 8, 2, 'Grilled', 47, '2009-03-15', 'Uma negociacao extremamente tensa acontece.'),
(45, 8, 3, 'Bit by a Dead Bee', 47, '2009-03-22', 'Walter tenta voltar a rotina normal.'),
(46, 8, 4, 'Down', 47, '2009-03-29', 'As relacoes pessoais comecam a ruir.'),
(47, 8, 5, 'Breakage', 47, '2009-04-05', 'O negocio cresce e os problemas tambem.'),
(48, 8, 6, 'Peekaboo', 47, '2009-04-12', 'Jesse encontra uma situacao delicada.'),
-- Arcane S1
(49, 9, 1, 'Welcome to the Playground', 43, '2021-11-06', 'As irmas Vi e Powder vivem um conflito entre cidades.'),
(50, 9, 2, 'Some Mysteries Are Better Left Unsolved', 40, '2021-11-06', 'Uma nova ameaca surge no caminho de Powder.'),
(51, 9, 3, 'The Base Violence Necessary for Change', 43, '2021-11-06', 'As tensoes politicas aumentam.'),
(52, 9, 4, 'Happy Progress Day!', 41, '2021-11-13', 'Piltover celebra enquanto novos problemas aparecem.'),
(53, 9, 5, 'Everybody Wants to Be My Enemy', 41, '2021-11-13', 'As perseguicoes ficam cada vez mais intensas.'),
(54, 9, 6, 'When These Walls Come Tumbling Down', 44, '2021-11-20', 'As duas cidades enfrentam novas consequencias.'),
-- Arcane S2
(55, 10, 1, 'Heavy Is the Crown', 41, '2024-11-09', 'As consequencias da primeira temporada se aprofundam.'),
(56, 10, 2, 'Watch It All Burn', 41, '2024-11-09', 'Novos conflitos ameacam as cidades.'),
(57, 10, 3, 'Finally Got the Name Right', 42, '2024-11-16', 'Alianças improvaveis surgem.'),
(58, 10, 4, 'Paint the Town Blue', 43, '2024-11-16', 'Uma nova estrategia muda o equilibrio.'),
(59, 10, 5, 'Blisters and Bedrock', 42, '2024-11-23', 'As perdas geram novas decisoes.'),
(60, 10, 6, 'The Dirt Under Your Nails', 45, '2024-11-23', 'O conflito se aproxima de seu desfecho.');

-- ---------------------------------------------------------
-- 5.6 Gêneros (8 registros)
-- ---------------------------------------------------------
INSERT INTO genero
(id_genero, nome)
VALUES
(1, 'Drama'),
(2, 'Comédia'),
(3, 'Ficção Científica'),
(4, 'Fantasia'),
(5, 'Suspense'),
(6, 'Crime'),
(7, 'Ação'),
(8, 'Mistério');

-- ---------------------------------------------------------
-- 5.7 Associação série-gênero
-- Todas as séries da carga possuem pelo menos um gênero.
-- ---------------------------------------------------------
INSERT INTO serie_genero (id_serie, id_genero)
VALUES
(1, 3), (1, 5), (1, 8),
(2, 2), (2, 1),
(3, 1), (3, 3), (3, 8),
(4, 1), (4, 6), (4, 5),
(5, 4), (5, 7), (5, 1);

-- ---------------------------------------------------------
-- 5.8 Pessoas (10 registros)
-- ---------------------------------------------------------
INSERT INTO pessoa
(id_pessoa, nome, data_nascimento, nacionalidade)
VALUES
(1, 'Winona Ryder', '1971-10-29', 'EUA'),
(2, 'David Harbour', '1975-04-10', 'EUA'),
(3, 'Matt Duffer', '1984-02-15', 'EUA'),
(4, 'Ricky Gervais', '1961-06-25', 'Reino Unido'),
(5, 'Jenna Fischer', '1974-03-07', 'EUA'),
(6, 'Bryan Cranston', '1956-03-07', 'EUA'),
(7, 'Vince Gilligan', '1967-02-10', 'EUA'),
(8, 'Hailee Steinfeld', '1996-12-11', 'EUA'),
(9, 'Christian Linke', '1979-08-10', 'Alemanha'),
(10, 'Louis Hofmann', '1997-06-03', 'Alemanha');

-- ---------------------------------------------------------
-- 5.9 Participações
-- Uma pessoa exerce funções variadas; em atores, personagem é
-- obrigatório; nas demais funções, permanece NULL (RN10).
-- ---------------------------------------------------------
INSERT INTO participacao
(id_pessoa, id_serie, funcao, personagem)
VALUES
(1, 1, 'ator', 'Joyce Byers'),
(2, 1, 'ator', 'Jim Hopper'),
(3, 1, 'criador', NULL),
(3, 1, 'roteirista', NULL),
(4, 2, 'criador', NULL),
(4, 2, 'roteirista', NULL),
(5, 2, 'ator', 'Pam Beesly'),
(6, 4, 'ator', 'Walter White'),
(7, 4, 'criador', NULL),
(7, 4, 'roteirista', NULL),
(8, 5, 'ator', 'Vi'),
(9, 5, 'criador', NULL),
(9, 5, 'roteirista', NULL),
(10, 3, 'ator', 'Jonas Kahnwald');

-- ---------------------------------------------------------
-- 5.10 Estados declarados
-- Registros de exibição inseridos na sequência podem alterar os
-- estados para 'assistindo' através da RN14.
-- ---------------------------------------------------------
INSERT INTO estado_serie
(id_usuario, id_serie, estado, data_atualizacao)
VALUES
(1, 1, 'watchlist',  '2026-02-10'),
(1, 2, 'watchlist',  '2026-02-11'),
(1, 4, 'abandonada', '2026-02-12'),
(2, 2, 'watchlist',  '2026-02-12'),
(2, 5, 'watchlist',  '2026-02-13'),
(3, 3, 'watchlist',  '2026-02-14'),
(3, 5, 'abandonada', '2026-02-15'),
(4, 1, 'watchlist',  '2026-02-16'),
(5, 4, 'watchlist',  '2026-02-17'),
(6, 5, 'watchlist',  '2026-02-18');

-- ---------------------------------------------------------
-- 5.11 Registros de exibição (56 eventos)
-- Estes registros vêm antes das avaliações de episódio (RN18).
-- O evento duplicado do episódio 1 em datas diferentes demonstra RN11.
-- O gatilho RN14 promove automaticamente o estado da série.
-- ---------------------------------------------------------
INSERT INTO registro
(id_registro, id_usuario, id_episodio, data_assistido)
VALUES
(1, 1, 1, '2026-03-01'),
(2, 1, 2, '2026-03-02'),
(3, 1, 3, '2026-03-03'),
(4, 1, 7, '2026-03-05'),
(5, 1, 8, '2026-03-06'),
(6, 1, 13, '2026-03-10'),
(7, 1, 14, '2026-03-11'),
(8, 1, 19, '2026-03-15'),
(9, 1, 25, '2026-03-20'),
(10, 1, 26, '2026-03-21'),
(11, 1, 1, '2026-04-01'),

(12, 2, 1, '2026-03-02'),
(13, 2, 4, '2026-03-03'),
(14, 2, 7, '2026-03-04'),
(15, 2, 13, '2026-03-08'),
(16, 2, 15, '2026-03-09'),
(17, 2, 20, '2026-03-12'),
(18, 2, 25, '2026-03-17'),
(19, 2, 31, '2026-03-22'),
(20, 2, 32, '2026-03-23'),

(21, 3, 2, '2026-03-04'),
(22, 3, 3, '2026-03-05'),
(23, 3, 5, '2026-03-06'),
(24, 3, 8, '2026-03-08'),
(25, 3, 14, '2026-03-10'),
(26, 3, 19, '2026-03-13'),
(27, 3, 26, '2026-03-18'),
(28, 3, 37, '2026-03-25'),
(29, 3, 38, '2026-03-26'),

(30, 4, 6, '2026-03-02'),
(31, 4, 9, '2026-03-04'),
(32, 4, 10, '2026-03-05'),
(33, 4, 16, '2026-03-09'),
(34, 4, 21, '2026-03-12'),
(35, 4, 27, '2026-03-16'),
(36, 4, 31, '2026-03-20'),
(37, 4, 43, '2026-03-27'),
(38, 4, 44, '2026-03-28'),

(39, 5, 1, '2026-03-03'),
(40, 5, 2, '2026-03-04'),
(41, 5, 11, '2026-03-12'),
(42, 5, 17, '2026-03-14'),
(43, 5, 23, '2026-03-18'),
(44, 5, 29, '2026-03-21'),
(45, 5, 33, '2026-03-24'),
(46, 5, 49, '2026-03-30'),
(47, 5, 50, '2026-03-31'),

(48, 6, 4, '2026-03-02'),
(49, 6, 7, '2026-03-05'),
(50, 6, 12, '2026-03-08'),
(51, 6, 18, '2026-03-13'),
(52, 6, 24, '2026-03-17'),
(53, 6, 30, '2026-03-20'),
(54, 6, 35, '2026-03-24'),
(55, 6, 55, '2026-03-30'),
(56, 6, 56, '2026-03-31');

-- ---------------------------------------------------------
-- 5.12 Avaliações (22 registros)
-- Há avaliações nos três níveis do acervo.
-- ---------------------------------------------------------
INSERT INTO avaliacao
(id_avaliacao, id_usuario, nota, texto, contem_spoiler, data_publicacao, tipo_alvo)
VALUES
(1,  1, 5.0, 'Excelente equilibrio entre misterio e aventura.', FALSE, '2026-04-02 10:00:00', 'serie'),
(2,  2, 4.5, 'Muito divertida e envolvente.', FALSE, '2026-04-03 11:00:00', 'serie'),
(3,  3, 4.0, 'A primeira temporada prende bastante.', FALSE, '2026-04-04 12:00:00', 'serie'),
(4,  4, 5.0, 'Uma das melhores comedias de escritorio.', FALSE, '2026-04-05 09:30:00', 'serie'),
(5,  5, 4.5, 'Humor bem construido e personagens marcantes.', FALSE, '2026-04-06 14:00:00', 'serie'),
(6,  6, 4.0, 'Muito boa, embora irregular em alguns momentos.', FALSE, '2026-04-07 15:00:00', 'serie'),
(7,  1, 4.5, 'Misterio complexo e atmosfera excelente.', FALSE, '2026-04-08 08:30:00', 'serie'),
(8,  2, 4.0, 'Exige bastante atencao do espectador.', TRUE,  '2026-04-09 16:00:00', 'serie'),
(9,  3, 3.5, 'Otimo drama, mas tem um ritmo mais lento.', FALSE, '2026-04-10 13:00:00', 'serie'),
(10, 4, 4.0, 'Visual muito marcante e historia interessante.', FALSE, '2026-04-11 18:00:00', 'serie'),

(11, 5, 5.0, 'Temporada muito consistente.', FALSE, '2026-04-12 10:00:00', 'temporada'),
(12, 6, 4.0, 'Boa evolucao da historia.', FALSE, '2026-04-13 11:00:00', 'temporada'),
(13, 1, 4.5, 'Excelente desenvolvimento de personagens.', TRUE,  '2026-04-14 12:00:00', 'temporada'),
(14, 2, 4.0, 'Boa temporada, com alguns episodios fortes.', FALSE, '2026-04-15 13:00:00', 'temporada'),
(15, 3, 4.5, 'A trama fica muito mais ambiciosa.', TRUE, '2026-04-16 14:00:00', 'temporada'),
(16, 4, 3.5, 'Interessante, mas nao foi minha favorita.', FALSE, '2026-04-17 15:00:00', 'temporada'),

(17, 1, 5.0, 'Piloto muito eficiente.', FALSE, '2026-04-18 09:00:00', 'episodio'),
(18, 2, 4.0, 'Bom episodio para apresentar o universo.', FALSE, '2026-04-18 10:00:00', 'episodio'),
(19, 3, 4.5, 'Gostei bastante da construcao de tensao.', FALSE, '2026-04-18 11:00:00', 'episodio'),
(20, 4, 4.0, 'Otimo desenvolvimento do conflito.', TRUE, '2026-04-18 12:00:00', 'episodio'),
(21, 5, 4.5, 'O episodio apresenta bem os personagens.', FALSE, '2026-04-18 13:00:00', 'episodio'),
(22, 6, 5.0, 'Um dos meus episodios favoritos.', TRUE, '2026-04-18 14:00:00', 'episodio');

-- ---------------------------------------------------------
-- 5.13 Associação das avaliações aos alvos
-- A avaliação de episódio só é inserida depois dos registros de
-- exibição, pois o gatilho RN18 consulta a tabela registro.
-- ---------------------------------------------------------
INSERT INTO avaliacao_serie (id_avaliacao, id_serie)
VALUES
(1,1),(2,1),(3,1),
(4,2),(5,2),(6,2),
(7,3),(8,3),
(9,4),(10,5);

INSERT INTO avaliacao_temporada (id_avaliacao, id_temporada)
VALUES
(11,2),
(12,4),
(13,5),
(14,6),
(15,7),
(16,9);

INSERT INTO avaliacao_episodio (id_avaliacao, id_episodio)
VALUES
(17,1),
(18,13),
(19,19),
(20,21),
(21,23),
(22,30);

-- ---------------------------------------------------------
-- 5.14 Curtidas
-- O conjunto foi montado para produzir ranking de popularidade
-- e desempates naturais entre avaliações.
-- O trigger atualiza avaliacao.total_curtidas automaticamente.
-- ---------------------------------------------------------
INSERT INTO curtida (id_usuario, id_avaliacao, data_curtida)
VALUES
(2,1,'2026-04-19 09:00:00'), (3,1,'2026-04-19 09:05:00'), (4,1,'2026-04-19 09:10:00'),
(1,2,'2026-04-19 09:15:00'), (3,2,'2026-04-19 09:20:00'), (5,2,'2026-04-19 09:25:00'),
(1,3,'2026-04-19 09:30:00'), (2,3,'2026-04-19 09:35:00'), (4,3,'2026-04-19 09:40:00'),
(1,4,'2026-04-19 09:45:00'), (2,4,'2026-04-19 09:50:00'), (6,4,'2026-04-19 09:55:00'),
(2,5,'2026-04-19 10:00:00'), (3,5,'2026-04-19 10:05:00'), (4,5,'2026-04-19 10:10:00'),
(1,6,'2026-04-19 10:15:00'), (3,6,'2026-04-19 10:20:00'), (5,6,'2026-04-19 10:25:00'),
(2,7,'2026-04-19 10:30:00'), (4,7,'2026-04-19 10:35:00'), (6,7,'2026-04-19 10:40:00'),
(1,8,'2026-04-19 10:45:00'), (3,8,'2026-04-19 10:50:00'), (5,8,'2026-04-19 10:55:00'),
(1,9,'2026-04-19 11:00:00'), (2,9,'2026-04-19 11:05:00'), (6,9,'2026-04-19 11:10:00'),
(2,10,'2026-04-19 11:15:00'), (3,10,'2026-04-19 11:20:00'), (5,10,'2026-04-19 11:25:00'),
(1,11,'2026-04-19 11:30:00'), (3,11,'2026-04-19 11:35:00'),
(2,12,'2026-04-19 11:40:00'), (4,12,'2026-04-19 11:45:00'),
(4,13,'2026-04-19 11:50:00'), (5,13,'2026-04-19 11:55:00'),
(1,14,'2026-04-19 12:00:00'), (6,14,'2026-04-19 12:05:00'),
(2,15,'2026-04-19 12:10:00'), (6,15,'2026-04-19 12:15:00'),
(1,16,'2026-04-19 12:20:00'), (5,16,'2026-04-19 12:25:00'),
(2,17,'2026-04-19 12:30:00'), (4,17,'2026-04-19 12:35:00'),
(1,18,'2026-04-19 12:40:00'), (3,18,'2026-04-19 12:45:00'),
(2,19,'2026-04-19 12:50:00'), (5,19,'2026-04-19 12:55:00'),
(1,20,'2026-04-19 13:00:00'), (6,20,'2026-04-19 13:05:00'),
(3,21,'2026-04-19 13:10:00'), (6,21,'2026-04-19 13:15:00'),
(1,22,'2026-04-19 13:20:00'), (4,22,'2026-04-19 13:25:00');

-- ---------------------------------------------------------
-- 5.15 Comentários e respostas
-- Respostas utilizam o FK composto para garantir RN23:
-- o comentário-pai deve pertencer à mesma avaliação.
-- ---------------------------------------------------------
INSERT INTO comentario
(id_comentario, id_avaliacao, id_usuario, id_comentario_pai, texto, data_publicacao)
VALUES
(1, 1, 2, NULL, 'Concordo, a atmosfera da serie e muito boa.', '2026-04-20 09:00:00'),
(2, 1, 3, 1, 'Principalmente nas primeiras temporadas.', '2026-04-20 09:10:00'),
(3, 1, 4, NULL, 'Tambem gostei bastante da ambientacao.', '2026-04-20 09:20:00'),
(4, 4, 1, NULL, 'Essa serie sempre melhora meu humor.', '2026-04-20 09:30:00'),
(5, 4, 5, 4, 'O elenco ajuda muito nisso.', '2026-04-20 09:40:00'),
(6, 7, 2, NULL, 'A historia exige atencao, mas vale a pena.', '2026-04-20 09:50:00'),
(7, 9, 1, NULL, 'O ritmo realmente e mais lento.', '2026-04-20 10:00:00'),
(8, 17, 3, NULL, 'Achei o piloto muito bem amarrado.', '2026-04-20 10:10:00');


-- ---------------------------------------------------------
-- 5.16 Ajuste das sequências de identidade
-- Como a carga utiliza IDs explícitos para deixar as referências
-- didáticas, reposicionamos as sequências após a inserção dos dados.
-- Assim, novos INSERTs que omitam o ID continuam funcionando.
-- ---------------------------------------------------------
SELECT setval(pg_get_serial_sequence('usuario', 'id_usuario'), COALESCE(MAX(id_usuario), 1)) FROM usuario;
SELECT setval(pg_get_serial_sequence('serie', 'id_serie'), COALESCE(MAX(id_serie), 1)) FROM serie;
SELECT setval(pg_get_serial_sequence('temporada', 'id_temporada'), COALESCE(MAX(id_temporada), 1)) FROM temporada;
SELECT setval(pg_get_serial_sequence('episodio', 'id_episodio'), COALESCE(MAX(id_episodio), 1)) FROM episodio;
SELECT setval(pg_get_serial_sequence('genero', 'id_genero'), COALESCE(MAX(id_genero), 1)) FROM genero;
SELECT setval(pg_get_serial_sequence('pessoa', 'id_pessoa'), COALESCE(MAX(id_pessoa), 1)) FROM pessoa;
SELECT setval(pg_get_serial_sequence('registro', 'id_registro'), COALESCE(MAX(id_registro), 1)) FROM registro;
SELECT setval(pg_get_serial_sequence('avaliacao', 'id_avaliacao'), COALESCE(MAX(id_avaliacao), 1)) FROM avaliacao;
SELECT setval(pg_get_serial_sequence('comentario', 'id_comentario'), COALESCE(MAX(id_comentario), 1)) FROM comentario;

-- =========================================================
-- 6. CONSULTAS DE EXEMPLO
-- =========================================================

-- ---------------------------------------------------------
-- Consulta 1 - Ranking de séries por nota média
-- Pergunta: quais séries possuem as melhores avaliações, considerando
-- apenas as que receberam número significativo de notas?
-- Conteúdo exercitado: JOIN, AVG, COUNT, GROUP BY, HAVING, ORDER BY.
-- O HAVING >= 3 evita que uma única nota alta domine o ranking.
-- ---------------------------------------------------------
SELECT
    id_serie,
    titulo_alvo AS serie,
    ROUND(AVG(nota), 2) AS nota_media,
    COUNT(*) AS quantidade_notas
FROM vw_avaliacao_completa
WHERE tipo_alvo = 'serie'
  AND nota IS NOT NULL
GROUP BY id_serie, titulo_alvo
HAVING COUNT(*) >= 3
ORDER BY nota_media DESC, quantidade_notas DESC, serie;

-- ---------------------------------------------------------
-- Consulta 2 - Atividade recente de quem o usuário segue
-- Pergunta: quais foram as últimas avaliações publicadas pelos usuários
-- que o usuário 1 segue?
-- Conteúdo exercitado: subconsulta IN, auto-relacionamento segue e visão.
-- ---------------------------------------------------------
SELECT
    username,
    tipo_alvo,
    titulo_alvo,
    nota,
    data_publicacao
FROM vw_avaliacao_completa
WHERE id_usuario IN (
    SELECT id_seguido
    FROM segue
    WHERE id_seguidor = 1
)
ORDER BY data_publicacao DESC
LIMIT 10;

-- Formulação equivalente usando EXISTS:
SELECT
    v.username,
    v.tipo_alvo,
    v.titulo_alvo,
    v.nota,
    v.data_publicacao
FROM vw_avaliacao_completa v
WHERE EXISTS (
    SELECT 1
    FROM segue sg
    WHERE sg.id_seguidor = 1
      AND sg.id_seguido = v.id_usuario
)
ORDER BY v.data_publicacao DESC
LIMIT 10;

-- ---------------------------------------------------------
-- Consulta 3 - Séries na lista de interesse ainda não iniciadas
-- Pergunta: quais séries o usuário 1 marcou como 'watchlist' sem
-- ter assistido a nenhum episódio?
-- Conteúdo exercitado: operação de conjunto EXCEPT.
-- ---------------------------------------------------------
SELECT
    s.id_serie,
    s.titulo
FROM estado_serie es
JOIN serie s
  ON s.id_serie = es.id_serie
WHERE es.id_usuario = 2
  AND es.estado = 'watchlist'

EXCEPT

SELECT DISTINCT
    s.id_serie,
    s.titulo
FROM estado_serie es
JOIN serie s
  ON s.id_serie = es.id_serie
JOIN temporada t
  ON t.id_serie = s.id_serie
JOIN episodio e
  ON e.id_temporada = t.id_temporada
JOIN registro r
  ON r.id_episodio = e.id_episodio
 AND r.id_usuario = es.id_usuario
WHERE es.id_usuario = 1;

-- Formulação equivalente usando NOT EXISTS:
SELECT
    s.id_serie,
    s.titulo
FROM estado_serie es
JOIN serie s
  ON s.id_serie = es.id_serie
WHERE es.id_usuario = 2
  AND es.estado = 'watchlist'
  AND NOT EXISTS (
      SELECT 1
      FROM temporada t
      JOIN episodio e
        ON e.id_temporada = t.id_temporada
      JOIN registro r
        ON r.id_episodio = e.id_episodio
       AND r.id_usuario = es.id_usuario
      WHERE t.id_serie = s.id_serie
  );

-- =========================================================
-- FIM DO SCRIPT
-- =========================================================
